name: Release Workflow
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - name: Install dependencies
      run: |
        go mod download
        go get github.com/goreleaser/goreleaser@v0.186.0
        sudo apt-get install -y rpm
    - name: Build and package for release
      run: |
        goreleaser --rm-dist
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: FSTEVE22/SuperCalculator:${{ github.ref }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
